/**
 * Screen definitions generated from the reference product's page structure.
 *
 * Columns and field lists only - no markup or styling is taken from the
 * source. Screens render through our own T02 and T05 templates.
 *
 * Regenerate with: python scripts/generate-screen-defs.py
 */

import type { FormFieldDef } from '@garage/ui'

export interface ScreenDef {
  title: string
  columns: string[]
  fields: FormFieldDef[]
}

export const screenDefs: Record<string, ScreenDef> = {
  'accountant-add': {
    title: 'Add Accountant',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'accountant-list': {
    title: 'Accountants',
    columns: ['Image', 'First Name', 'Last Name', 'Email', 'Mobile Number'],
    fields: [],
  },
  'addons': {
    title: 'Addons',
    columns: [],
    fields: [],
  },
  'branch-list': {
    title: 'Branch',
    columns: [],
    fields: [],
  },
  'branchadmin-add': {
    title: 'Add Branch Admin',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'branchadmin-list': {
    title: 'Branch Admin',
    columns: [],
    fields: [],
  },
  'color-list': {
    title: 'Colors',
    columns: ['Name', 'Color'],
    fields: [],
  },
  'compliances-list': {
    title: 'Compliances',
    columns: [],
    fields: [],
  },
  'customer-add': {
    title: 'Add Customer',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'tax_id', label: 'Tax', type: 'select' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'customer-list': {
    title: 'Customer List',
    columns: ['Image', 'First Name', 'Last Name', 'Email', 'Mobile Number', 'Vehicle List'],
    fields: [],
  },
  'customfields-list': {
    title: 'Custom Fields',
    columns: [],
    fields: [],
  },
  'dashboard': {
    title: 'Dashboard : Admin',
    columns: [],
    fields: [],
  },
  'email-templates': {
    title: 'Email Templates',
    columns: [],
    fields: [],
  },
  'employee-add': {
    title: 'Add Employees',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'join_date', label: 'Join Date', type: 'date' },
      { name: 'designation', label: 'Designation', type: 'select' },
      { name: 'left_date', label: 'Left Date', type: 'date' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'employee-list': {
    title: 'Employees',
    columns: ['Image', 'First Name', 'Last Name', 'Email', 'Mobile Number'],
    fields: [],
  },
  'expense-add': {
    title: 'Add Expense',
    columns: [],
    fields: [
      { name: 'main_label', label: 'Main Label', type: 'text', required: true },
      { name: 'status', label: 'Status', type: 'select', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'expense_entry', label: 'Expense Entry', type: 'number', required: true },
      { name: 'expense_label', label: 'Expense Label', type: 'text' },
    ],
  },
  'expense-list': {
    title: 'Expenses',
    columns: [],
    fields: [],
  },
  'gatepass-add': {
    title: 'Add Gatepass',
    columns: [],
    fields: [
      { name: 'jobcard', label: 'Jobcard', type: 'select', required: true },
      { name: 'gatepass_no', label: 'Gatepass No', type: 'text' },
      { name: 'Customername', label: 'Customername', type: 'select', required: true },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'vehiclename', label: 'Vehiclename', type: 'text' },
      { name: 'veh_type', label: 'Veh Type', type: 'select' },
      { name: 'chassis', label: 'Chassis', type: 'text' },
      { name: 'kms', label: 'Kms', type: 'text' },
      { name: 'out_date', label: 'Out Date', type: 'date', required: true },
    ],
  },
  'gatepass-list': {
    title: 'Gate Pass',
    columns: ['Gatepass No.', 'Job No.', 'Customer Name', 'Vehicle Name'],
    fields: [],
  },
  'helpdocument-list': {
    title: 'Help Document',
    columns: [],
    fields: [],
  },
  'how-to-videos': {
    title: 'How To Videos',
    columns: [],
    fields: [],
  },
  'income-add': {
    title: 'Add Income',
    columns: [],
    fields: [
      { name: 'invoice', label: 'Invoice', type: 'select', required: true },
      { name: 'Total_Amount', label: 'Total Amount', type: 'money' },
      { name: 'paymentno', label: 'Paymentno', type: 'text' },
      { name: 'cus_id', label: 'Cus', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', required: true },
      { name: 'main_label', label: 'Main Label', type: 'text', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'Payment_type', label: 'Payment Type', type: 'select' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'income_entry', label: 'Income Entry', type: 'text', required: true },
      { name: 'income_label', label: 'Income Label', type: 'text' },
    ],
  },
  'income-list': {
    title: 'Income',
    columns: ['Customer Name', 'Invoice Number', 'Amount ($)', 'Payment Type', 'Date', 'Main Label'],
    fields: [],
  },
  'invoice-add': {
    title: 'Add Invoice',
    columns: [],
    fields: [
      { name: 'Invoice_type', label: 'Invoice Type', type: 'select' },
      { name: 'Invoice_Number', label: 'Invoice Number', type: 'text' },
      { name: 'paymentno', label: 'Paymentno', type: 'text' },
      { name: 'Customer', label: 'Customer', type: 'select', required: true },
      { name: 'Job_card', label: 'Job Card', type: 'select', required: true },
      { name: 'jobcard_no', label: 'Jobcard No', type: 'text' },
      { name: 'Total_Amount', label: 'Total Amount', type: 'money' },
      { name: 'Date', label: 'Date', type: 'date', required: true },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'Status', label: 'Status', type: 'select', required: true },
      { name: 'grandtotal', label: 'Grandtotal', type: 'money' },
      { name: 'paidamount', label: 'Paidamount', type: 'money' },
      { name: 'Payment_type', label: 'Payment Type', type: 'select' },
      { name: 'Details', label: 'Details', type: 'textarea' },
      { name: 'Discount', label: 'Discount', type: 'text' },
      { name: 'Tax', label: 'Tax', type: 'select' },
    ],
  },
  'invoice-list': {
    title: 'Invoices',
    columns: ['Invoice Number', 'Customer Name', 'Jobcard Number', 'Number Plate', 'Total Amount ($)', 'Paid Amount ($)', 'Date', 'Status'],
    fields: [],
  },
  'jobcard-list': {
    title: 'JobCard',
    columns: ['Job Card No.', 'Service Type', 'Customer Name', 'Assign To', 'Service Date', 'Upcoming Service Date', 'Status'],
    fields: [],
  },
  'notes-list': {
    title: 'Notes',
    columns: [],
    fields: [],
  },
  'observation-list': {
    title: 'Observation Library',
    columns: [],
    fields: [],
  },
  'partsells-list': {
    title: 'Part Sells',
    columns: ['Bill Number', 'Customer Name', 'Date', 'Part Brand', 'Salesman'],
    fields: [],
  },
  'payment-list': {
    title: 'Payment Method',
    columns: ['Payment Type'],
    fields: [],
  },
  'product-add': {
    title: 'Product Add',
    columns: [],
    fields: [
      { name: 'p_no', label: 'P No', type: 'text' },
      { name: 'p_date', label: 'P Date', type: 'date' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'p_type', label: 'P Type', type: 'select' },
      { name: 'warranty', label: 'Warranty', type: 'text' },
      { name: 'unit', label: 'Unit', type: 'select', required: true },
      { name: 'sup_id', label: 'Sup', type: 'select' },
      { name: 'color', label: 'Color', type: 'select' },
      { name: 'price', label: 'Price', type: 'money', required: true },
      { name: 'Discount', label: 'Discount', type: 'text' },
      { name: 'Tax', label: 'Tax', type: 'select' },
      { name: 'margin', label: 'Margin', type: 'text' },
      { name: 'hsn_sac_code', label: 'Hsn Sac Code', type: 'number' },
      { name: 'sellingprice', label: 'Sellingprice', type: 'money' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'product_type', label: 'Product Type', type: 'select' },
      { name: 'c_name', label: 'Colour Name', type: 'text' },
      { name: 'c_code', label: 'Colour Code', type: 'text' },
      { name: 'unit_measurement', label: 'Unit Measurement', type: 'text' },
    ],
  },
  'product-list': {
    title: 'Product',
    columns: ['Image', 'Product Number', 'M.Name', 'Product Name', 'Price ($)', 'Selling Price ($)', 'HS/HSN/SAC', 'Supplier Name', 'Company Name', 'Color'],
    fields: [],
  },
  'purchase-add': {
    title: 'Purchase Add',
    columns: ['Manufacturer Name (*)', 'Product Name (*)', 'Quantity', 'Price ($)', 'Amount ($)'],
    fields: [
      { name: 'p_no', label: 'P No', type: 'text' },
      { name: 'p_date', label: 'P Date', type: 'date', required: true },
      { name: 's_name', label: 'S Name', type: 'select', required: true },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'product', label: 'Product', type: 'select' },
      { name: 'row_number', label: 'Row Number', type: 'text' },
    ],
  },
  'purchase-list': {
    title: 'Purchase',
    columns: ['Purchase Code', 'Supplier Name', 'Email', 'Mobile', 'Date', 'Products'],
    fields: [],
  },
  'quotation-add': {
    title: 'Add Quotation',
    columns: [],
    fields: [
      { name: 'jobno', label: 'Jobno', type: 'text' },
      { name: 'Customername', label: 'Customername', type: 'select', required: true },
      { name: 'vehicalname', label: 'Vehicalname', type: 'select', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'repair_cat', label: 'Repair Cat', type: 'select', required: true },
      { name: 'service_type', label: 'Service Type', type: 'select', required: true },
      { name: 'charge', label: 'Charge', type: 'text', required: true },
      { name: 'details', label: 'Details', type: 'textarea' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'washbay', label: 'Washbay', type: 'text' },
      { name: 'washBayCharge', label: 'WashBayCharge', type: 'text', required: true },
      { name: 'motTestStatusCheckbox', label: 'MotTestStatusCheckbox', type: 'select' },
      { name: 'motTestCharge', label: 'MotTestCharge', type: 'text', required: true },
      { name: 'Tax', label: 'Tax', type: 'select' },
      { name: 'inspection', label: 'Inspection', type: 'select' },
      { name: 'firstname', label: 'First Name', type: 'text', required: true },
      { name: 'lastname', label: 'Last Name', type: 'text', required: true },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'mobile', label: 'Mobile Number', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'text', required: true },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'country_id', label: 'Country', type: 'select', required: true },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea', required: true },
      { name: 'customer_id', label: 'Customer', type: 'select' },
      { name: 'vehical_id', label: 'Vehicle', type: 'select', required: true },
      { name: 'branch_vehicle', label: 'Branch Vehicle', type: 'select' },
      { name: 'number_plate', label: 'Number Plate', type: 'text', required: true },
      { name: 'vehicabrand', label: 'Vehicle Brand', type: 'select' },
      { name: 'chasicno', label: 'Chassis No', type: 'text' },
      { name: 'modelname', label: 'Model Name', type: 'select', required: true },
      { name: 'modelyear', label: 'Model Year', type: 'select' },
      { name: 'fueltype', label: 'Fuel Type', type: 'select' },
      { name: 'gearno', label: 'Gear No', type: 'text' },
      { name: 'odometerreading', label: 'Odometer Reading', type: 'text' },
      { name: 'dom', label: 'Date of Manufacturing', type: 'text' },
      { name: 'gearbox', label: 'Gearbox', type: 'select' },
      { name: 'gearboxno', label: 'Gearbox No', type: 'select' },
      { name: 'engineno', label: 'Engine No', type: 'text' },
      { name: 'enginesize', label: 'Engine Size', type: 'text' },
      { name: 'keyno', label: 'Key No', type: 'text' },
      { name: 'engine', label: 'Engine', type: 'text' },
      { name: 'model_name', label: 'Model Name', type: 'select', required: true },
      { name: 'vehical_type', label: 'Vehicle Type', type: 'select', required: true },
      { name: 'vehical_brand', label: 'Vehicle Brand', type: 'select', required: true },
      { name: 'fuel_type', label: 'Fuel Type', type: 'select', required: true },
      { name: 'repair_category_name', label: 'Repair Category Name', type: 'text' },
    ],
  },
  'quotation-list': {
    title: 'Quotation',
    columns: ['Quotation #', 'Customer Name', 'Date', 'Service Category', 'Assign To', 'Number Plate', 'Price ($)', 'Status'],
    fields: [],
  },
  'reports-service': {
    title: 'Reports',
    columns: ['Job No.', 'Customer Name', 'Date', 'Vehicle Name', 'Service Type', 'Paid Amount ($)', 'Assign To'],
    fields: [],
  },
  'service-add': {
    title: 'Add Services',
    columns: [],
    fields: [
      { name: 'jobno', label: 'Jobno', type: 'text' },
      { name: 'Customername', label: 'Customername', type: 'select', required: true },
      { name: 'vehicalname', label: 'Vehicalname', type: 'select', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'repair_cat', label: 'Repair Cat', type: 'select', required: true },
      { name: 'AssigneTo', label: 'AssigneTo', type: 'select', required: true },
      { name: 'service_type', label: 'Service Type', type: 'select', required: true },
      { name: 'charge', label: 'Charge', type: 'text', required: true },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'details', label: 'Details', type: 'textarea' },
      { name: 'kms', label: 'Kms', type: 'text', required: true },
      { name: 'washbay', label: 'Washbay', type: 'text' },
      { name: 'washBayCharge', label: 'WashBayCharge', type: 'text', required: true },
      { name: 'motTestStatusCheckbox', label: 'MotTestStatusCheckbox', type: 'select' },
      { name: 'motTestCharge', label: 'MotTestCharge', type: 'text', required: true },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'markers', label: 'Markers', type: 'text' },
      { name: 'car_details', label: 'Car Details', type: 'textarea' },
      { name: 'firstname', label: 'First Name', type: 'text', required: true },
      { name: 'lastname', label: 'Last Name', type: 'text', required: true },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'mobile', label: 'Mobile Number', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'text', required: true },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'company_name', label: 'Company Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'country_id', label: 'Country', type: 'select', required: true },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea', required: true },
      { name: 'customer_id', label: 'Customer', type: 'select' },
      { name: 'vehical_id', label: 'Vehicle', type: 'select', required: true },
      { name: 'branch_vehicle', label: 'Branch Vehicle', type: 'select' },
      { name: 'number_plate', label: 'Number Plate', type: 'text', required: true },
      { name: 'vehicabrand', label: 'Vehicle Brand', type: 'select' },
      { name: 'chasicno', label: 'Chassis No', type: 'text' },
      { name: 'modelname', label: 'Model Name', type: 'select', required: true },
      { name: 'price', label: 'Price', type: 'money' },
      { name: 'modelyear', label: 'Model Year', type: 'select' },
      { name: 'fueltype', label: 'Fuel Type', type: 'select' },
      { name: 'gearno', label: 'Gear No', type: 'text' },
      { name: 'odometerreading', label: 'Odometer Reading', type: 'text' },
      { name: 'dom', label: 'Date of Manufacturing', type: 'text' },
      { name: 'gearbox', label: 'Gearbox', type: 'select' },
      { name: 'gearboxno', label: 'Gearbox No', type: 'select' },
      { name: 'engineno', label: 'Engine No', type: 'text' },
      { name: 'enginesize', label: 'Engine Size', type: 'text' },
      { name: 'keyno', label: 'Key No', type: 'text' },
      { name: 'engine', label: 'Engine', type: 'text' },
      { name: 'model_name', label: 'Model Name', type: 'select', required: true },
      { name: 'vehical_type', label: 'Vehicle Type', type: 'select', required: true },
      { name: 'vehical_brand', label: 'Vehicle Brand', type: 'select', required: true },
      { name: 'fuel_type', label: 'Fuel Type', type: 'select', required: true },
      { name: 'repair_category_name', label: 'Repair Category Name', type: 'text' },
    ],
  },
  'service-list': {
    title: 'Services',
    columns: ['Job #', 'Customer Name', 'Date', 'Service Category', 'Upcoming Service Date', 'Assign To', 'Free Service Coupen', 'Number Plate'],
    fields: [],
  },
  'settings-general': {
    title: 'General Settings',
    columns: [],
    fields: [
      { name: 'System_Name', label: 'System Name', type: 'text', required: true },
      { name: 'start_year', label: 'Start Year', type: 'text' },
      { name: 'Phone_Number', label: 'Phone Number', type: 'text', required: true },
      { name: 'Email', label: 'Email', type: 'text', required: true },
      { name: 'address', label: 'Address', type: 'textarea', required: true },
      { name: 'country_id', label: 'Country', type: 'select', required: true },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'Logo_Image', label: 'Logo Image', type: 'upload' },
      { name: 'Cover_Image', label: 'Cover Image', type: 'upload' },
    ],
  },
  'settings-profile': {
    title: 'Profile Setting',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text', required: true },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
    ],
  },
  'stock-list': {
    title: 'Stock List',
    columns: ['Image', 'Product Number', 'Manufacturer Name', 'Product Name', 'Quantity', 'Unit Of Measurement'],
    fields: [],
  },
  'supplier-add': {
    title: 'Add Supplier',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'supplier-list': {
    title: 'Suppliers',
    columns: ['Image', 'First Name', 'Last Name', 'Company Name', 'Email', 'Product Name'],
    fields: [],
  },
  'supportstaff-add': {
    title: 'Add Supportstaff',
    columns: [],
    fields: [
      { name: 'firstname', label: 'First Name', type: 'text' },
      { name: 'lastname', label: 'Last Name', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'password_confirmation', label: 'Confirm Password', type: 'text' },
      { name: 'mobile', label: 'Mobile Number', type: 'text' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'dob', label: 'Date of Birth', type: 'date' },
      { name: 'displayname', label: 'Display Name', type: 'text' },
      { name: 'landlineno', label: 'Landline No', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'country_id', label: 'Country', type: 'select' },
      { name: 'state_id', label: 'State', type: 'select' },
      { name: 'city', label: 'City', type: 'select' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  'supportstaff-list': {
    title: 'Support Staffs',
    columns: ['Image', 'First Name', 'Last Name', 'Email', 'Mobile Number'],
    fields: [],
  },
  'taxrates-list': {
    title: 'Tax Rates',
    columns: ['Account Tax Name Tax Rates(%)', 'Tax Number'],
    fields: [],
  },
  'vehicle-add': {
    title: 'Add Vehicle',
    columns: ['Description'],
    fields: [
      { name: 'vhi_for', label: 'Vehicle For', type: 'text' },
      { name: 'vehical_id', label: 'Vehicle', type: 'select', required: true },
      { name: 'number_plate', label: 'Number Plate', type: 'text' },
      { name: 'vehicabrand', label: 'Vehicle Brand', type: 'select' },
      { name: 'price', label: 'Price', type: 'money' },
      { name: 'customer', label: 'Customer', type: 'select' },
      { name: 'fueltype', label: 'Fuel Type', type: 'select', required: true },
      { name: 'gearno', label: 'Gear No', type: 'text' },
      { name: 'modelname', label: 'Model Name', type: 'select', required: true },
      { name: 'modelyear', label: 'Model Year', type: 'select' },
      { name: 'branch', label: 'Branch', type: 'select' },
      { name: 'dom', label: 'Date of Manufacturing', type: 'text' },
      { name: 'gearbox', label: 'Gearbox', type: 'select' },
      { name: 'gearboxno', label: 'Gearbox No', type: 'select' },
      { name: 'engineno', label: 'Engine No', type: 'text' },
      { name: 'enginesize', label: 'Engine Size', type: 'text' },
      { name: 'keyno', label: 'Key No', type: 'text' },
      { name: 'engine', label: 'Engine', type: 'text' },
      { name: 'chasicno', label: 'Chassis No', type: 'text' },
      { name: 'odometerreading', label: 'Odometer Reading', type: 'text' },
      { name: 'image', label: 'Image', type: 'upload' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'color', label: 'Color', type: 'select' },
      { name: 'vehical_type', label: 'Vehicle Type', type: 'select', required: true },
      { name: 'vehical_brand', label: 'Vehicle Brand', type: 'select', required: true },
      { name: 'fuel_type', label: 'Fuel Type', type: 'select', required: true },
      { name: 'model_name', label: 'Model Name', type: 'select', required: true },
      { name: 'c_name', label: 'Colour Name', type: 'text' },
      { name: 'c_code', label: 'Colour Code', type: 'text' },
    ],
  },
  'vehicle-list': {
    title: 'Vehicles',
    columns: ['Image', 'Type', 'Model Name', 'Number Plate', 'Customer Name', 'Date Of Manufacturing', 'Last Service Date', 'Upcoming Service Date', 'Engine No'],
    fields: [],
  },
  'vehiclebrand-list': {
    title: 'Vehicle Brand',
    columns: ['Vehicle Type', 'Vehicle Brand'],
    fields: [],
  },
  'vehiclemodel-list': {
    title: 'Vehicle Model',
    columns: ['Vehicle Brand', 'Vehicle Model'],
    fields: [],
  },
  'vehicletype-list': {
    title: 'Vehicle Type',
    columns: ['Vehicle Type'],
    fields: [],
  },
}
